export const PLACE_FIELDS = Object.freeze({
  NAME: 'name',
  PLACE_ID: 'placeID',
  PLUS_CODE: 'plusCode',
  COORDINATE: 'coordinate',
  OPENING_HOURS: 'openingHours',
  PHONE_NUMBER: 'phoneNumber',
  TYPES: 'types',
  PRICE_LEVEL: 'priceLevel',
  WEBSITE: 'website',
  VIEWPORT: 'viewport',
  FORMATTED_ADDRESS: 'formattedAddress',
  ADDRESS_COMPONENTS: 'addressComponents',
  RATING: 'rating',
  USER_RATINGS_TOTAL: 'userRatingsTotal',
  UTC_OFFSET_MINUTES: 'useOffsetMinutes',
  BUSINESS_STATUS: 'businessStatus',
  ICONS_IMAGE_URL: 'iconImageURL',
  TAKEOUT: 'takeout',
  DELIVERY: 'delivery',
  DINE_IN: 'dineIn',
  CURBSIDE_PICKUP: 'curbsidePickup',
  PHOTOS: 'photos',
});
